{
  parserClass="top.totoro.plugin.test.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="top.totoro.plugin.test"
  psiImplPackage="top.totoro.plugin.test.impl"

  elementTypeHolderClass="top.totoro.plugin.test.SimpleTypes"
  elementTypeClass="top.totoro.plugin.test.SimpleElementType"
  tokenTypeClass="top.totoro.plugin.test.SimpleTokenType"

  psiImplUtilClass="top.totoro.plugin.test.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF|TAG)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin="top.totoro.plugin.test.SimpleNamedElementImpl"
  implements="top.totoro.plugin.test.SimpleNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier]
}